# Generated by Django 2.0.7 on 2018-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zufang_info',
            name='img',
            field=models.CharField(default='', max_length=300),
        ),
    ]
