# Generated by Django 2.0.7 on 2018-07-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0003_auto_20180726_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='zufang_info',
            name='jjr_phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
