# Generated by Django 2.0.7 on 2018-07-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0004_zufang_info_jjr_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zufang_content_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('month_money', models.CharField(max_length=100)),
                ('mianji', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=300)),
                ('jjr_img', models.CharField(max_length=300)),
                ('jjr', models.CharField(max_length=200)),
                ('jjr_phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
