# Generated by Django 2.0.7 on 2018-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0005_zufang_content_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zufang_content_info',
            name='id',
        ),
        migrations.AddField(
            model_name='zufang_content_info',
            name='info_id',
            field=models.IntegerField(db_column='FId', default=1, primary_key=True, serialize=False),
        ),
    ]
