# Generated by Django 2.0.7 on 2018-07-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0006_auto_20180726_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zufang_content_info',
            name='img',
        ),
        migrations.RemoveField(
            model_name='zufang_content_info',
            name='mianji',
        ),
        migrations.RemoveField(
            model_name='zufang_content_info',
            name='month_money',
        ),
        migrations.RemoveField(
            model_name='zufang_content_info',
            name='title',
        ),
    ]
