# Generated by Django 2.0.7 on 2018-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0010_auto_20180726_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='zufang_info',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='zufang_info',
            name='city_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
