# Generated by Django 2.0.7 on 2018-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0011_auto_20180727_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zufang_url',
            fields=[
                ('url_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('next_url', models.CharField(max_length=300)),
            ],
        ),
    ]
